// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SiteYonetimi.Infrastructure.Data;

#nullable disable

namespace SiteYonetimi.Infrastructure.Migrations
{
    [DbContext(typeof(SharedTenantDbContext))]
    [Migration("20260608000001_AddBuildingImportFields")]
    partial class AddBuildingImportFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
